---
abstract: 'create QR codes for display in the terminal'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Term-QRCode-Compact
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: '5'
  Getopt::Long: '0'
  Imager::QRCode: '0'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/Term-QRCode-Compact/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/Term-QRCode-Compact.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
